site_name: tree-sitter-loongdoc
repo_name: tree-sitter-loongdoc
repo_url: https://github.com/cathaysia/tree-sitter-loongdoc
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
