name: bench

on:
  workflow_dispatch:
  push:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'
  pull_request:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'

permissions:
  contents: write

jobs:
  fuzz:
    name: bench parsers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        parser: [tree-sitter-asciidoc, tree-sitter-asciidoc_inline]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache bench result
        uses: actions/cache@v3
        with:
          path: |
            ${{matrix.parser}}/target/criterion/
          key: bench-${{matrix.parser}}-${{ runner.os }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: oaper environment
        run: |
          cd ${{matrix.parser}}
          git clone https://github.com/asciidoctor/asciidoctor.git
      - name: bench ${{matrix.parser}} parser
        run: |
          cd ${{matrix.parser}}
          cargo bench
      - name: publish bench result
        uses: Wandalen/wretry.action@master
        with:
          action: peaceiris/actions-gh-pages@v4
          with: |
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ${{ matrix.parser }}/target/criterion
            destination_dir: bench_${{ matrix.parser }}
