name: bench

on:
  workflow_dispatch:
  push:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'
  pull_request:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'

permissions:
  contents: write

jobs:
  fuzz:
    name: bench parsers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache bench result
        uses: actions/cache@v3
        with:
          path: |
            target/criterion/
          key: bench-${{ runner.os }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: paper environment
        run: |
          git clone https://github.com/asciidoctor/asciidoctor.git
      - name: bench parser
        run: |
          cargo bench
      - name: publish bench result
        uses: Wandalen/wretry.action@master
        with:
          action: peaceiris/actions-gh-pages@v4
          with: |
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: target/criterion
            destination_dir: benchmark
