name: bench

on:
  workflow_dispatch:
  push:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'
  pull_request:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  fuzz:
    name: bench parsers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache bench result
        uses: actions/cache@v4
        with:
          path: |
            target/criterion
          key: bench-${{ runner.os }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: paper environment
        run: |
          git clone https://github.com/asciidoctor/asciidoctor.git
          base64 /dev/urandom | head -c 1048576 > 1mb.data
          base64 /dev/urandom | head -c 8388608 > 8mb.data
          base64 /dev/urandom | head -c 67108864 > 64mb.data
          base64 /dev/urandom | head -c 134217728 > 128mb.data
      - name: bench parser
        run: |
          cargo bench
      - name: publish bench result
        uses: Wandalen/wretry.action@master
        with:
          action: peaceiris/actions-gh-pages@v4
          with: |
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: target/criterion
            destination_dir: benchmark
