name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'
  pull_request:
    paths:
      - 'common/*'
      - '*/grammar.js'
      - '*/src/**'
      - '*/test/**'

jobs:
  fuzz:
    name: Fuzz parsers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        parser: [tree-sitter-asciidoc, tree-sitter-asciidoc_inline]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-fuzz
        run: |
          cargo install cargo-fuzz
      - name: Fuzz ${{matrix.parser}} parser
        run: |
          cd ${{matrix.parser}}
          cargo +nightly fuzz run parse -- -max_total_time=300
