name: playground

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  crates:
    name: publish crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: v20.12.2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-emscripten
      - name: build wasm
        env:
          CC: emcc
        run: |
          make wasm
          cp ./target/wasm32-unknown-emscripten/debug/loongdoc.* playground/public/
      - name: build playground
        run: |
          cd playground
          pnpm install
          pnpm build
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playground/out
          publish_branch: gh-playground
          keep_files: true
